export function hashCode(str) {
  let hash = 0;
  for (let i = 0, len = str.length; i < len; i++) {
    let chr = str.charCodeAt(i);
    hash = (hash << 5) - hash + chr;
    hash |= 0; // Convert to 32bit integer
  }
  return hash.toString();
}

export const languages = {
  afrikaans: 'af',
  aragonese: 'an',
  bulgarian: 'bg',
  bosnian: 'bs',
  catalan: 'ca',
  czech: 'cs',
  welsh: 'cy',
  danish: 'da',
  german: 'de',
  greek: 'el',
  default: 'en',
  english: 'en-gb',
  en_scottish: 'en-sc',
  english_north: 'en-uk-north',
  english_rp: 'en-uk-rp',
  english_wmids: 'en-uk-wmids',
  english_us: 'en-us',
  en_westindies: 'en-wi',
  esperanto: 'eo',
  spanish: 'es',
  spanish_latin_am: 'es-la',
  estonian: 'et',
  persian: 'fa',
  persian_pinglish: 'fa-pin',
  finnish: 'fi',
  french_Belgium: 'fr-be',
  french: 'fr-fr',
  irish_gaeilge: 'ga',
  greek_ancient: 'grc',
  hindi: 'hi',
  croatian: 'hr',
  hungarian: 'hu',
  armenian: 'hy',
  armenian_west: 'hy-west',
  indonesian: 'id',
  icelandic: 'is',
  italian: 'it',
  lojban: 'jbo',
  georgian: 'ka',
  kannada: 'kn',
  kurdish: 'ku',
  latin: 'la',
  lingua_franca_nova: 'lfn',
  lithuanian: 'lt',
  latvian: 'lv',
  macedonian: 'mk',
  malayalam: 'ml',
  malay: 'ms',
  nepali: 'ne',
  dutch: 'nl',
  norwegian: 'no',
  punjabi: 'pa',
  polish: 'pl',
  brazil: 'pt-br',
  portugal: 'pt-pt',
  romanian: 'ro',
  russian: 'ru',
  slovak: 'sk',
  albanian: 'sq',
  serbian: 'sr',
  swedish: 'sv',
  swahili_test: 'sw',
  tamil: 'ta',
  turkish: 'tr',
  vietnam: 'vi',
  vietnam_hue: 'vi-hue',
  vietnam_sgn: 'vi-sgn',
  Mandarin: 'zh',
  cantonese: 'zh-yue'
};
